GET http://localhost:3000/search?title=Avengers%20Endgame
content-type: application/json
###
GET http://localhost:3000/search?id=tt4154796
content-type: application/json
###
POST http://localhost:3000/users/register
content-type: application/json

{
    "username": "myUsername",
    "password": "myPassword",
    "email": "myEmail"
}
###
GET http://localhost:3000/users/login?username=myUsername&password=myPassword
content-type: application/json
###
GET http://localhost:3000/users/logout
content-type: application/json
###