POST http://localhost:3000/users/register
content-type: application/json

{
    "username": "myUsername",
    "password": "myPa55word!",
    "email": "myEmail",
    "firstName": "myFirstName",
    "lastName": "myLastName"
}
###
GET http://localhost:3000/users/login?username=myUsername&password=myPa55word!
content-type: application/json
###
GET http://localhost:3000/users/logout
content-type: application/json
###
PUT http://localhost:3000/users/update
content-type: application/json

{
    "username": "myUsername3"
}
###
DELETE  http://localhost:3000/users/remove
content-type: application/json

{
    "password": "myPa55word!"
}