GET http://localhost:3000/users/login?username=myUsername&password=myPa55word!
###
content-type: application/json
###
GET http://localhost:3000/lists/wish-list
content-type: application/json
###
POST http://localhost:3000/lists/add-to-wish-list
content-type: application/json

{
    "title": "Django Unchained",
    "year": 2012,
    "imdbId": "tt1853728",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg"
}
###
DELETE http://localhost:3000/lists/remove-from-wish-list
content-type: application/json

{
    "imdbId": "tt1853728"
}
###
GET http://localhost:3000/users/logout
content-type: application/json
###